### ISSUE TITLE
[2월 2일~2월 5일] 김준태 TODO

### ISSUE THREAD

**Issue by JJinTae** [TeamUbermensch/Loanword-detector#3]
- [x] 아이디어 회의
- [x] 분석 자료 탐구
- [x] Python 개발 환경 구축
- [x] Python 형태소 분석기 조사 및 파악
