### ISSUE TITLE
[2월 2일~2월 5일] 김연아 TODO

### ISSUE THREAD

**Issue by KimYeonAh** [TeamUbermensch/Loanword-detector#4]
- [ ] 아이디어 회의
- [ ] 분석 자료 탐구
- [ ] Python 개발 환경 구축
- [ ] 파이썬 형태소 분석기 조사 및 파악
